/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as ApprovalsVendorIdRouteImport } from './routes/approvals_.$vendorId'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors_.$vendorId'
import { Route as VendorsCompareRouteImport } from './routes/vendors_.compare'
import { Route as VendorsNewRouteImport } from './routes/vendors_.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsVendorIdRoute = ApprovalsVendorIdRouteImport.update({
  id: '/approvals_/$vendorId',
  path: '/approvals/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors_/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsCompareRoute = VendorsCompareRouteImport.update({
  id: '/vendors_/compare',
  path: '/vendors/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsNewRoute = VendorsNewRouteImport.update({
  id: '/vendors_/new',
  path: '/vendors/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/vendors': typeof VendorsRoute
  '/approvals/$vendorId': typeof ApprovalsVendorIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/compare': typeof VendorsCompareRoute
  '/vendors/new': typeof VendorsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/vendors': typeof VendorsRoute
  '/approvals/$vendorId': typeof ApprovalsVendorIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/vendors/compare': typeof VendorsCompareRoute
  '/vendors/new': typeof VendorsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/notifications': typeof NotificationsRoute
  '/performance': typeof PerformanceRoute
  '/vendors': typeof VendorsRoute
  '/approvals_/$vendorId': typeof ApprovalsVendorIdRoute
  '/vendors_/$vendorId': typeof VendorsVendorIdRoute
  '/vendors_/compare': typeof VendorsCompareRoute
  '/vendors_/new': typeof VendorsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/notifications'
    | '/performance'
    | '/vendors'
    | '/approvals/$vendorId'
    | '/vendors/$vendorId'
    | '/vendors/compare'
    | '/vendors/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/notifications'
    | '/performance'
    | '/vendors'
    | '/approvals/$vendorId'
    | '/vendors/$vendorId'
    | '/vendors/compare'
    | '/vendors/new'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/notifications'
    | '/performance'
    | '/vendors'
    | '/approvals_/$vendorId'
    | '/vendors_/$vendorId'
    | '/vendors_/compare'
    | '/vendors_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  NotificationsRoute: typeof NotificationsRoute
  PerformanceRoute: typeof PerformanceRoute
  VendorsRoute: typeof VendorsRoute
  ApprovalsVendorIdRoute: typeof ApprovalsVendorIdRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
  VendorsCompareRoute: typeof VendorsCompareRoute
  VendorsNewRoute: typeof VendorsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals_/$vendorId': {
      id: '/approvals_/$vendorId'
      path: '/approvals/$vendorId'
      fullPath: '/approvals/$vendorId'
      preLoaderRoute: typeof ApprovalsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors_/$vendorId': {
      id: '/vendors_/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors_/compare': {
      id: '/vendors_/compare'
      path: '/vendors/compare'
      fullPath: '/vendors/compare'
      preLoaderRoute: typeof VendorsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors_/new': {
      id: '/vendors_/new'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof VendorsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  NotificationsRoute: NotificationsRoute,
  PerformanceRoute: PerformanceRoute,
  VendorsRoute: VendorsRoute,
  ApprovalsVendorIdRoute: ApprovalsVendorIdRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
  VendorsCompareRoute: VendorsCompareRoute,
  VendorsNewRoute: VendorsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
